name: Pull Request Conventions

# ------------------------------------------------------------------------------
# Workflow Settings
# ------------------------------------------------------------------------------

on:
  workflow_dispatch:

permissions: {}

jobs: {}
